with-expecter: true
dir: "{{.InterfaceDirRelative}}"
filename: "mock_{{.InterfaceName | snakecase }}.go"
inpackage: true

packages:
  github.com/brentellingson/learning-golang-api/internal/controller:
    config:
      all: true
