# volumes:
#   postgres-data:
volumes:
  go-pkg:
    name: go-pkg
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env

    volumes:
      - ../..:/workspaces:cached
      - go-pkg:/go/pkg

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:keycloak

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.2
    command: start-dev
    restart: unless-stopped
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - .env

    # run keylocak on same network as application, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:app
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
